### ISSUE TITLE
批量操作删除错误

### ISSUE THREAD

**Issue by bbeyes** [ali-sdk/ots2#18]
### 调用batchWriteRow接口批量删除行，如果 delete_rows 中不指定attribute_columns会产生以下错误：
```
Cannot convert undefined or null to object
at exports.$ (node_modules/@alicloud/ots2/lib/helper.js:191:21)
at hook (node_modules/@alicloud/ots2/lib/actions.js:329:29)
at Client.exports.batchWriteRow (node_modules/@alicloud/ots2/lib/actions.js:350:5)
```

### delete_rows 中指定attribute_columns则产生以下错误：
```
.com.aliyun.openservices.ots.protocol.DeleteRowInBatchWriteRowRequest#attribute_columns is not a field: undefined
```

### ots2.proto相关定义：
```
message DeleteRowInBatchWriteRowRequest {
    required Condition condition = 1;
    repeated Column primary_key = 2;
    // 无attribute_columns字段
}
```

### action.js相关代码：
```
var hook = function (rows) {
  if (!rows) {
    return;
  }

  for (var i = 0; i < rows.length; i++) {
    var row = rows[i];
    row.primary_key = $(row.primary_key);
    row.attribute_columns = $(row.attribute_columns); // 错误可能和这里有关
  }
};

exports.batchWriteRow = function* (tables) {
  for (var i = 0; i < tables.length; i++) {
    var table = tables[i];
    hook(table.put_rows);
    hook(table.update_rows);
    hook(table.delete_rows); // 错误可能和这里有关
  }

  return yield this.request('BatchWriteRow', {
    tables: tables
  });
};
```

**Comment by JacksonTian** [comment]
收到。

**Comment by JacksonTian** [comment]
麻烦你手工安装下 https://github.com/ali-sdk/ots2/pull/19 的 issue18 分支，确定下。

稍后我会找环境测试下。

**Comment by bbeyes** [comment]
3q。安装使用后未发现异常。

**Comment by JacksonTian** [comment]
已经发布新的版本。
