### ISSUE TITLE
ECONNRESET 错误

### ISSUE THREAD

**Issue by bbeyes** [ali-sdk/ots2#24]
调用GetRange接口偶尔（大概几千次出现一次）会抛出以下异常，多台服务器上都出现这种情况。该异常能判断出是哪一方的问题么？
```
getrange: { 
  Error: socket hang up POST http://*.cn-hangzhou.ots-internal.aliyuncs.com/GetRange failed.
  at createHangUpError (_http_client.js:254:15)
  at Socket.socketOnEnd (_http_client.js:346:23)
  at emitNone (events.js:91:20)
  at Socket.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET' 
}
```

## ots2 Version

1.5.4

## Node.js Version

8.4.0

**Comment by JacksonTian** [comment]
服务端断开了。
