### ISSUE TITLE
getRange 里面没有 filter的功能吗

### ISSUE THREAD

**Issue by puregardenia** [ali-sdk/ots2#4]
我想要通过where查询条件(非主键的属性列) 查询 ，官网上的GetRange有filter功能，现在ots2没有这个功能吗
```javascript
Error: .com.aliyun.cloudservice.ots2.GetRangeRequest#filter is not a field: undefined
      at MessagePrototype.set (d:\Node\node_statics\node_modules\protobufjs\dist\ProtoBuf.js:2539:35)
      at MessagePrototype.set (d:\Node\node_statics\node_modules\protobufjs\dist\ProtoBuf.js:2533:38)
      at Message (d:\Node\node_statics\node_modules\protobufjs\dist\ProtoBuf.js:2462:34)
      at Client.request (d:\Node\node_statics\node_modules\ots2\lib\client.js:97:17)
      at Client.request.next (<anonymous>)
      at onFulfilled (d:\Node\node_statics\node_modules\co\index.js:65:19)
      at d:\Node\node_statics\node_modules\co\index.js:54:5
      at co (d:\Node\node_statics\node_modules\co\index.js:50:10)
      at toPromise (d:\Node\node_statics\node_modules\co\index.js:118:63)
      at next (d:\Node\node_statics\node_modules\co\index.js:99:29)

```

**Comment by puregardenia** [comment]
@JacksonTian

**Comment by JacksonTian** [comment]
我来实现。

**Comment by JacksonTian** [comment]
@puregardenia 我研究了下，filter功能目前依赖OTS未公开的协议。

**Comment by puregardenia** [comment]
好吧，不过我看到官方的 php sdk 最近刚实现了这个功能。

https://help.aliyun.com/document_detail/27353.html?spm=5176.doc27351.6.685.qwgdcJ

不知道这个有没有帮助

**Comment by JacksonTian** [comment]
简单点来说就是协议未公开，java和php sdk是ots产品内部的人放出来的实现，他们内部知道协议。

**Comment by JacksonTian** [comment]
协议公开了。已经实现。

```
+ @alicloud/ots2@1.4.0
```

具体使用方式可以参见仓库中的测试用例。

```js
    var name = 'metrics';
    var primaryKeys = {uid: 'test_uid'};
    var columns = ['test', 'integer', 'double', 'boolean', 'binary'];
    var filter = OTS.makeFilter('uid == @uid false', {uid: OTS.createString('test_uid')});
    var response = yield client.getRow(name, primaryKeys, columns, filter);
```

**Comment by puregardenia** [comment]
多谢，辛苦了！ @JacksonTian

**Comment by puregardenia** [comment]
`@alicloud/ots2` 版本的项目 npm install 后缺少`index.js`文件 [查看](https://github.com/ali-sdk/ots2/tree/filter)

**Comment by JacksonTian** [comment]
现在已经没有index.js文件了呀。

**Comment by puregardenia** [comment]
`npm install @alicloud/ots2 --save` 后, 文件和filter分支的文件不一样， 比如package.json 中的`main`属性 就是  `"main": "./index"` @JacksonTian

**Comment by JacksonTian** [comment]
Sorry, 是files的配置，导致index.js文件没有发布到npm上。

1.5.2 修复了这个问题。
